spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:sqlserver://localhost:1433;encrypt=false;database=ourdb;trustServerCertificate=true
    username: sa
    password: CorrectHorseBatteryStapleFor$
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
